Liveの一覧ページ作成
atsuya02/ohv_app pull request #23
Opened 2021-06-22 08:47 UTC by atsuya02

2021-06-23 08:56 UTC, atsuya02 commented
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/73219274/123067851-51359080-d44c-11eb-8b9f-245e18c9f87c.png">
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/73219274/123067899-5c88bc00-d44c-11eb-9920-26797d778fb9.png">

2021-06-23 08:57 UTC, atsuya02 commented
@YuyaYoshioka 
確認お願い！

2021-06-23 09:31 UTC, atsuya02 commented
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/73219274/123073240-36194f80-d451-11eb-97d9-deacfcf394e0.png">
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/73219274/123073281-3e718a80-d451-11eb-8205-242ecb708951.png">

2021-06-23 09:34 UTC, atsuya02 commented
@YuyaYoshioka 
確認お願い！
https://ohv.herokuapp.com/live_page

2021-06-23 15:31 UTC, YuyaYoshioka commented on app/models/live.rb
> +  scope :recently_live_date, -> { order(start_time: :desc) }
「最近のライブの日付」になってしまうから，`recently_held_live`とか？

2021-06-23 15:35 UTC, YuyaYoshioka commented on app/controllers/live_pages_controller.rb
> +                      Live.recently_live_date.first(5)
直近のライブやから，`first(5)`まで，`recently_live_date`に入れても良さそう

2021-06-23 16:14 UTC, YuyaYoshioka commented on app/controllers/live_pages_controller.rb
> +                    end
ここのif文やめたい
```
@date = params[:live_date] || -Float::INFINITY..Float::INFINITY
@filter_lives = Live.where(start_time: @date.in_time_zone.all_month).recently_live_date.first(5)
```
とか？
[ref](https://qiita.com/gotchane/items/1d6069c2bd4ecd5c386b)

2021-06-24 16:31 UTC, YuyaYoshioka commented on app/controllers/live_pages_controller.rb
> +      end
```
@date = params[:live_date]&.in_time_zone&.all_month || (-Float::INFINITY..Float::INFINITY)
@filter_lives = Live.where(start_time: @date).recently_live_date

lives = Live.recently_live_date
@live_date_list = lives.map do |live|
  view_date = live.start_time.strftime("%Y-%m")
  filter_date = live.start_time.in_time_zone.all_month
  [view_date, filter_date]
end.concat([["recent live", -Float::INFINITY..Float::INFINITY]]).to_set
```
こんな感じ？

2021-06-24 16:32 UTC, YuyaYoshioka commented on app/controllers/live_pages_controller.rb
> +      end
```
@date = params[:live_date]&.in_time_zone&.all_month || (-Float::INFINITY..Float::INFINITY)
@filter_lives = Live.where(start_time: @date).recently_live_date

lives = Live.recently_live_date
@live_date_list = lives.map do |live|
  view_date = live.start_time.strftime("%Y-%m")
  filter_date = live.start_time.in_time_zone.all_month
  [view_date, filter_date]
end.concat([["recent live", -Float::INFINITY..Float::INFINITY]]).to_set
```
こんな感じ？

2021-06-24 16:36 UTC, YuyaYoshioka commented on app/controllers/live_pages_controller.rb
> +      end
```
lives = Live.recently_live_date
@live_date_list = lives.map do |live|
  view_date = live.start_time.strftime("%Y-%m")
  filter_date = live.start_time.in_time_zone.all_month
  [view_date, filter_date]
end.concat([["recent live", -Float::INFINITY..Float::INFINITY]]).to_set
```
ここは，表示に関するロジックになるやろうから，別のクラスに切り出したいから，view objectとか使うといいかも
https://techracho.bpsinc.jp/hachi8833/2021_01_07/14738#view-object

2021-06-24 16:47 UTC, YuyaYoshioka commented on app/controllers/live_pages_controller.rb
> +      end
`app/models/view_objects/live_date_view_object.rb`っていうファイル作って，
```
class LiveDateViewObject
  def self.live_dates
    recently_lives = Live.recently_live_date
    live_dates = recently_lives.map do |live|
      view_date = live.start_time.strftime("%Y-%m")
      filter_date = live.start_time.in_time_zone.all_month
      [view_date, filter_date]
    end
    ([["recent live", -Float::INFINITY..Float::INFINITY]] + live_dates).to_set
  end
end
```
みたいに書いてもいいかも

view_object自体は
```
@live_date_list = LiveDateViewObject.live_dates
```
で呼び出せばいい

2021-06-24 16:48 UTC, YuyaYoshioka requested changes
レビューしたよ
ライブ一覧ページ表示するところは，最新のライブだけ5件取得するのではなく，ページネーション導入しよう

2021-06-24 16:51 UTC, YuyaYoshioka commented on app/controllers/live_pages_controller.rb
> +      end
最終的には，
```
# frozen_string_literal: true

class LivePagesController < ApplicationController
  def show
    @date = params[:live_date]&.in_time_zone&.all_month || (-Float::INFINITY..Float::INFINITY)
    @filter_lives = Live.where(start_time: @date).recently_live_date
    @live_date_list = LiveDateViewObject.live_dates
  end
end
```
になる

2021-06-24 17:53 UTC, atsuya02 commented
ページネーション導入するなら、ライブ一覧ページ表示する所の名前を"recent live"から"all_live"に変更する？

2021-06-24 17:56 UTC, YuyaYoshioka commented
どこのこと言ってる？
基本的にコード上で指摘してくれた方がわかりやすい

2021-06-24 18:01 UTC, atsuya02 commented on app/controllers/live_pages_controller.rb
> +    @live_date_list = [["recent live", ""]]
ページネーション導入するなら、ライブ一覧ページ表示する所の名前を"recent live"から"all_live"に変更する？
ここやね

2021-06-24 18:26 UTC, YuyaYoshioka commented on app/controllers/live_pages_controller.rb
> +    @live_date_list = [["recent live", ""]]
そうしよう

2021-06-25 15:20 UTC, atsuya02 commented
修正終わったよ

2021-06-25 17:01 UTC, YuyaYoshioka commented on spec/models/live_spec.rb
> +  end
`spec/view_objects/live_date_view_objects`
にテスト書こう

2021-06-25 17:01 UTC, YuyaYoshioka requested changes
レビューしたよ
ページネーションは良さそう

2021-06-25 17:35 UTC, YuyaYoshioka approved these changes
LGTM

2021-06-25 17:45 UTC, merged